### ISSUE TITLE
UnboundLocalError: local variable 'uniBar' referenced before assignment [$15]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#45]
File: `convert_csv_to_mt.py`

This [build](https://travis-ci.org/EA31337/FX-MT-VM/jobs/118724416) shows the error:

```
Converting the 5m timeframe
[INFO] Trying to read data from /dev/stdin...
Traceback (most recent call last):
  File "/home/travis/.wine/drive_c/Program Files (x86)/MetaTrader 4/history/downloads/scripts/convert_csv_to_mt.py", line 415, in <module>
    HST574(CSV(args.inputFile), outputPath, timeframe, symbol)
  File "/home/travis/.wine/drive_c/Program Files (x86)/MetaTrader 4/history/downloads/scripts/convert_csv_to_mt.py", line 203, in __init__
    bars += self._packUniBar(uniBar)
UnboundLocalError: local variable 'uniBar' referenced before assignment
```

This could be related to the recent changes.

**Comment by LemonBoy** [comment]
Nope, both in [1] and [2] you've introduced the same error probably after copy-pasting that section of code over. I don't know the format exactly but if it's a paste mishap I think the last line should just be deleted.

[1] https://github.com/FX31337/FX-BT-Scripts/blob/master/convert_csv_to_mt.py#L157,L162
[2] https://github.com/FX31337/FX-BT-Scripts/blob/master/convert_csv_to_mt.py#L198,L203

**Comment by kenorb** [comment]
This [build](https://travis-ci.org/EA31337/FX-MT-VM/jobs/119034504) fails now with:

	Traceback (most recent call last):
	  File "/home/travis/.wine/drive_c/Program Files (x86)/MetaTrader 4/history/downloads/scripts/convert_csv_to_mt.py", line 416, in <module>
	    FXT(CSV(args.inputFile), outputPath, timeframe, server, symbol, spread)
	  File "/home/travis/.wine/drive_c/Program Files (x86)/MetaTrader 4/history/downloads/scripts/convert_csv_to_mt.py", line 256, in __init__
	    header += pack('<i', int(firstUniBar['barTimestamp']))                          # Modelling start date - date of the first tick.
	TypeError: 'NoneType' object is not subscriptable

**Comment by LemonBoy** [comment]
The error is similar to the one fixed in the commit but completely different :)
As you can see in [1] it's possible that `firstUniBar` isn't ever initialized if there are no ticks, and this happens due to #25 

[1] https://github.com/FX31337/FX-BT-Scripts/blob/master/convert_csv_to_mt.py#L230,L244
