### ISSUE TITLE
Script to read accounts.ini binary data.

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#61]
1. Install [MT4](http://www.metatrader4.com/en/download).
2. Run and open folder from menu _File_ -> _Open Data Folder_.
3. Go to `config/` folder, you should have `accounts.ini` file created.

It changes on configuration changes related to accounts (e.g. _File_ -> _Login to Trade Account_) or when you create a demo account (_File_ -> _Open an Account_). It remembers the account number.

Examples: [accounts-files.zip](https://github.com/FX31337/FX-BT-Scripts/files/258360/accounts-files.zip)

**Comment by rikhtehgaran** [comment]
Hi i try your script on your sample files that you have put  

> 
> Examples: [accounts-files.zip](https://github.com/FX31337/FX-BT-Scripts/files/258360/accounts-files.zip).
> 

I have get this error: 
```
$ ./convert_dat.py -i accounts1.ini -o out
Traceback (most recent call last):
  File "/mnt/My/Temp/00/accounts-files/./convert_dat.py", line 125, in <module>
    matches = re.search(r"([a-z0-9]+)\.dat", args.input_file).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```
So i changed the line 125 to .ini: 
`matches = re.search(r"([a-z0-9]+)\.ini", args.input_file).groups()`

But i still get error:
```
$ ./convert_dat.py -i accounts1.ini -o out
Traceback (most recent call last):
  File "/mnt/My/Temp/00/accounts-files/./convert_dat.py", line 127, in <module>
    raise Exception("Error with md5 from filename")
Exception: Error with md5 from filename

```
I there any way to extract accounts.ini from mt4?

**Comment by kenorb** [comment]
The thing is, I don't know the exact format of accounts.ini, could be similar or not, so changing few lines won't help much.
